#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { Command } from 'commander';
import { loadConfig, scan, check, loadFiles, routePlan, applyPlan, readDocument, values, update, writeFile, safePath, assertKey, encode, duplicates, encryptFile, encryptedEdit, publicMetadata, isMetadata } from './index.js';
const program = new Command().enablePositionalOptions().name('envranger').description('Know your variables. Put them in their place.').version('0.3.0')
  .option('--cwd <directory>', 'Project root', '.');
const root = () => path.resolve(program.opts().cwd);
function config() { return loadConfig(root()); }
function files(opts: any): string[] {
  const cfg = config();
  if (opts.env && opts.profile) throw new Error('Choose --env or --profile, not both.');
  if (opts.profile) {
    if (!Object.hasOwn(cfg.profiles,opts.profile)) throw new Error(`Unknown profile: ${opts.profile}`);
    return cfg.profiles[opts.profile];
  }
  return [opts.env ?? cfg.envFile];
}
function input(command: Command): Command { return command.option('--env <file>', 'Input file (defaults to config envFile or .env)').option('--profile <name>', 'Load a configured profile; later files win').option('--keys-file <file>', 'Explicit private key file inside the project'); }
function edit(command: Command): Command { return command.option('--env <file>', 'Target file (defaults to config envFile or .env)').option('--write', 'Apply changes; default is a preview'); }
function output(value: unknown) { console.log(JSON.stringify(value,null,2)); }
function writeOrPreview(file: string, text: string, opts: any, keys: string[]) {
  const target = safePath(root(),file);
  const changed = !fs.existsSync(target) || fs.readFileSync(target,'utf8') !== text;
  if (opts.write && changed) writeFile(file,text,root());
  output({action:changed ? opts.write ? 'written' : 'preview' : 'unchanged', file, keys});
}
program.command('init').description('Create JSON config, blank local file and example; preserve existing files')
  .option('--framework <name>', 'node, vite, or next', 'node').option('--write', 'Create files')
  .action(async opts => {
    if (!['node','vite','next'].includes(opts.framework)) throw new Error('Framework must be node, vite or next.');
    const local = opts.framework === 'node' ? '.env' : '.env.local';
    const template = {scanDirs:['.'],ignore:['**/test/**','**/tests/**'],required:[],optional:[],deprecated:[],envFile:local,profiles:{development:[local]},routes:{}};
    const cfgPath = safePath(root(),'envranger.config.json');
    const cfg = fs.existsSync(cfgPath) ? config() : template;
    const result = await scan(cfg,root());
    const keys = [...new Set([...result.keys,...cfg.required])].sort();
    const blank = '# Generated by envRanger. Fill values locally; never commit secrets.\n' + keys.map(k => `${k}=`).join('\n') + '\n';
    for (const [file,content] of [['envranger.config.json',JSON.stringify(template,null,2)+'\n'],[cfg.envFile,blank],['.env.example',blank]]) {
      if (fs.existsSync(safePath(root(),file))) output({action:'preserved',file});
      else writeOrPreview(file,content,opts,keys);
    }
    const ignoreFile = safePath(root(),'.gitignore');
    const old = fs.existsSync(ignoreFile) ? fs.readFileSync(ignoreFile,'utf8') : '';
    const marker = '# envRanger local files';
    if (!old.includes(marker)) writeOrPreview('.gitignore',old + (old.endsWith('\n') || !old ? '' : '\n') + '\n'+marker+'\n.env\n.env.*\n!.env.example\n.envranger/\n',opts,[]);
  });
program.command('scan').description('Find static process.env and import.meta.env references').action(async () => output(await scan(config(),root())));
for (const name of ['check','doctor']) input(program.command(name).description('Validate required, used, empty and deprecated keys; exits 1 on failure'))
  .option('--strict','Compatibility flag; checks always fail when invalid')
  .option('--report','Write a keys-only JSON report to .envranger/report.json')
  .action(async opts => {
    const cfg = config(); const found = await scan(cfg,root()); const {env,sources}=loadFiles(root(),files(opts),{keysFile:opts.keysFile});
    const result = check(found.keys,env,cfg);
    const ok = !result.missing.length && !result.empty.length && !result.deprecated.length;
    const report = {ok,...result,sources};
    output(report);
    if (opts.report) writeFile('.envranger/report.json',JSON.stringify(report,null,2)+'\n',root());
    if (!ok) process.exitCode=1;
  });
input(program.command('list').description('List keys, masked state and source files')).action(opts => {
  const {env,sources}=loadFiles(root(),files(opts),{keysFile:opts.keysFile});
  output(Object.keys(env).sort().map(key=>({key,value:env[key] ? '[REDACTED]' : '[EMPTY]',source:sources[key]})));
});
input(program.command('get').description('Inspect a key; values stay masked unless --reveal is supplied').argument('<key>'))
  .option('--reveal','Print the raw value explicitly').action((key,opts)=>{
    assertKey(key); const {env}=loadFiles(root(),files(opts),{keysFile:opts.keysFile});
    if (!(key in env)) throw new Error(`Key not found: ${key}`);
    console.log(opts.reveal ? env[key] : env[key] ? '[REDACTED]' : '[EMPTY]');
  });
edit(program.command('set').description('Set a literal value; prefer --stdin for secrets').argument('<key>').argument('[value]'))
  .option('--stdin','Read the exact value from stdin, including any trailing newline').action((key,value,opts)=>{
    assertKey(key);
    if (opts.stdin && value !== undefined) throw new Error('Supply a value or --stdin, not both.');
    const val = opts.stdin ? fs.readFileSync(0,'utf8') : value;
    if (val === undefined) throw new Error('Supply a value (use an empty string for blank values) or --stdin.');
    const file=files(opts)[0]; writeOrPreview(file,encryptedEdit(readDocument(safePath(root(),file),true),key,val),opts,[key]);
  });
edit(program.command('unset').description('Remove one key; preserves unrelated entries').argument('<key>')).action((key,opts)=>{
  const file=files(opts)[0];writeOrPreview(file,encryptedEdit(readDocument(safePath(root(),file)),key),opts,[key]);
});
input(program.command('example').description('Sync blank placeholders from source and input file; never copy values'))
  .option('--out <file>','Destination (must end in .example)', '.env.example').option('--write','Apply changes')
  .action(async opts=>{
    if (!opts.out.endsWith('.example')) throw new Error('Example output must end in .example.');
    const cfg = config(); const found=await scan(cfg,root()); const {env}=loadFiles(root(),files(opts),{keysFile:opts.keysFile});
    const keys=[...new Set([...found.keys,...Object.keys(env),...cfg.required,...cfg.optional])].sort();
    writeOrPreview(opts.out,'# Environment contract. Copy locally and fill in your values.\n'+keys.map(k=>`${k}=`).join('\n')+'\n',opts,keys);
  });
program.command('types').description('Generate optional NodeJS.ProcessEnv declarations from static references')
  .option('--out <file>','Declaration destination','.envranger/env.d.ts').option('--write','Apply changes').action(async opts=>{
    if (!opts.out.endsWith('.d.ts')) throw new Error('Type output must end in .d.ts.');
    const cfg=config();const {keys}=await scan(cfg,root());const all=[...new Set([...keys,...cfg.required,...cfg.optional])].sort();
    writeOrPreview(opts.out,'export {};\ndeclare global {\n  namespace NodeJS {\n    interface ProcessEnv {\n'+all.map(k=>`      ${JSON.stringify(k)}?: string;`).join('\n')+'\n    }\n  }\n}\n',opts,all);
  });
input(program.command('route').description('Copy explicitly mapped keys into destination files; source is preserved'))
  .option('--overwrite','Allow replacing conflicting destination values').option('--plaintext','Explicitly allow decrypted output in unencrypted destination files').option('--write','Apply the routing plan').action(opts=>{
    const cfg=config();const {env}=loadFiles(root(),files(opts),{keysFile:opts.keysFile});const plan=routePlan(root(),cfg,env,!!opts.overwrite,{keysFile:opts.keysFile,allowPlaintext:!!opts.plaintext,encryptedSource:files(opts).some(file=>!!publicMetadata(readDocument(safePath(root(),file))))});
    if(opts.write) applyPlan(root(),plan);
    output({action:opts.write?'written':'preview',destinations:plan.map(({file,keys})=>({file,keys}))});
  });
program.command('profiles').description('Show configured profile paths and precedence').action(()=>output(config().profiles));
program.command('diff').description('Compare keys and changed values without displaying values').argument('<left>').argument('<right>').action((left,right)=>{
  const a=loadFiles(root(),[left]).env;const b=loadFiles(root(),[right]).env;
  output({onlyLeft:Object.keys(a).filter(k=>!(k in b)).sort(),onlyRight:Object.keys(b).filter(k=>!(k in a)).sort(),changed:Object.keys(a).filter(k=>k in b && a[k]!==b[k]).sort()});
});
program.command('merge').description('Combine files, later sources win; existing output requires --overwrite').argument('<dest>').argument('<files...>')
  .option('--overwrite','Allow replacing an existing destination').option('--plaintext','Allow decrypted input to be written as plaintext').option('--keys-file <file>','Private key file').option('--write','Apply changes').action((dest,sources,opts)=>{
    if(fs.existsSync(safePath(root(),dest))&&!opts.overwrite) throw new Error('Destination exists. Use --overwrite to replace it.');
    if (fs.existsSync(safePath(root(),dest)) && publicMetadata(readDocument(safePath(root(),dest)))) throw new Error('Use route to update encrypted destinations without changing their public key.');
    if (!opts.plaintext && sources.some((f:string)=>publicMetadata(readDocument(safePath(root(),f))))) throw new Error('Merging decrypted values requires --plaintext.');
    const {env}=loadFiles(root(),sources,{keysFile:opts.keysFile});const keys=Object.keys(env).sort();
    writeOrPreview(dest,keys.map(k=>`${k}=${encode(env[k])}`).join('\n')+'\n',opts,keys);
  });
input(program.command('lint').description('Check syntax and duplicate keys without modifying values')).action(opts=>{
  const results=files(opts).map(file=>({file,duplicates:duplicates(readDocument(safePath(root(),file)))}));output(results);
  if(results.some(r=>r.duplicates.length))process.exitCode=1;
});
input(program.command('run').description('Run a program with a profile; inherited process values win by default').argument('<command>').argument('[args...]'))
  .option('--override','Let file values replace inherited process values').allowUnknownOption().passThroughOptions()
  .action((command,args,opts)=>{
    const {env}=loadFiles(root(),files(opts),{keysFile:opts.keysFile});
    const inherited=Object.fromEntries(Object.entries(process.env).filter(([key])=>!isMetadata(key)));
    const child=spawnSync(command,args,{cwd:root(),stdio:'inherit',shell:false,env:opts.override?{...inherited,...env}:{...env,...inherited}});
    if(child.error)throw new Error('Could not start the requested executable. Check its path.');
    process.exitCode=child.status??1;
  });
input(program.command('encrypt').description('Encrypt a file with dotenvx; preserve its public key and keep the private key separate'))
  .option('--public-key <hex>', 'Use an existing recipient public key; never generate or request their private key')
  .option('--write','Apply encryption').action(opts=>{
    if(opts.profile) throw new Error('Encrypt one --env file at a time.');
    output(encryptFile(root(),files(opts)[0],{keysFile:opts.keysFile,publicKey:opts.publicKey,write:!!opts.write}));
  });
input(program.command('keys').description('Inspect saved public keys only; never print private keys')).action(opts=>{
  output(files(opts).map(file=>({file,publicKey:publicMetadata(readDocument(safePath(root(),file)))})));
});
// Register all commands before parsing. Errors never include file contents or raw values.
program.parseAsync().catch(error=>{
  const message = error?.code ? `File operation failed (${error.code}); check paths and permissions.` : error.message;
  console.error(`envRanger: ${message}`);process.exitCode=1;
});
